# Generated by Django 3.2.6 on 2022-06-05 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20220604_1646'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZakatDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserId', models.IntegerField()),
                ('Year', models.IntegerField()),
                ('ZakatRate', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('PW_PersonalCash_Hand_Bank_AmtVal', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('PW_PersonalCash_Hand_Bank_ZakatDue', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('PW_TotalValueof_Gold_silver_AmtVal', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('PW_TotalValueof_Gold_silver_ZakatDue', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('PW_TotalValueof_stocks_shares_bonds_AmtVal', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('PW_TotalValueof_stocks_shares_bonds_ZakatDue', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('PW_TotalcashValueof_retirement_pansion_AmtVal', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('PW_TotalcashValueof_retirement_pansion_ZakatDue', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('PW_Loans_tobe_recievable_AmtVal', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('PW_Loans_tobe_recievable_ZakatDue', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('PW_Other_expecected_recievables_AmtVal', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('PW_Other_expecected_recievables_ZakatDue', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('BW_BusinessCash_Hand_Bank_AmtVal', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('BW_BusinessCash_Hand_Bank_ZakatDue', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('BW_Netvalueof_business_tradegoods_AmtVal', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('BW_Netvalueof_business_tradegoods_ZakatDue', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('BW_Total_business_recievables_AmtVal', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('BW_Total_business_recievables_ZakatDue', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('BW_NetIncomefrom_business_exploitedassets_duringyear_AmtVal', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('BW_NetIncomefrom_business_exploitedassets_duringyear_ZakatDue', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('BW_Currentvalueof_held_realestateproperties_AmtVal', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('BW_Currentvalueof_held_realestateproperties_ZakatDue', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('BW_Zakat_Total_AmtVal', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('BW_Zakat_Total_ZakatDue', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('D_Outstanding_necessary_debts_AmtVal', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('D_Outstanding_necessary_debts_ZakatDue', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('D_Zakat_paid_in_advance_duringYear_ZakatDue', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('D_Total_Deductions_ZakatDue', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('D_Remaining_Zakat_Due_ZakatDue', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
            ],
        ),
    ]
