# Generated by Django 4.0.5 on 2022-06-08 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_zakatdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zakatdetails',
            name='UserId',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='zakatdetails',
            name='Year',
            field=models.IntegerField(null=True),
        ),
    ]
