# Generated by Django 4.0.5 on 2022-06-11 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_zakatdetails_userid_alter_zakatdetails_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usermapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField()),
                ('sub', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
