# Generated by Django 4.0.5 on 2022-06-11 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_usermapping'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermapping',
            old_name='sub',
            new_name='key',
        ),
    ]
