# Generated by Django 4.0.5 on 2022-06-13 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_sub_usermapping_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='zakatdetails',
            name='modified_date',
            field=models.DateTimeField(null=True),
        ),
    ]
