# Generated by Django 4.0.5 on 2022-06-23 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_zakatdetails_modified_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermapping',
            name='email_field',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='usermapping',
            name='name',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
