# Generated by Django 4.0.5 on 2022-06-24 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_usermapping_email_field_usermapping_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zakatdetails',
            name='ZakatRate',
            field=models.DecimalField(decimal_places=3, max_digits=15, null=True),
        ),
    ]
